apiVersion: "v1"
kind: "Template"
metadata:
  name: logging-mux-template-maker
  annotations:
    description: "Template to create template for mux"
    tags: "infrastructure"
objects:
- apiVersion: "v1"
  kind: "Template"
  metadata:
    name: logging-mux-template
    annotations:
      description: "Template for logging forward/enricher/aggregator/normalizer (FEAN) (aka multiplexor aka mux) deployment."
      tags: "infrastructure"
    labels:
      logging-infra: mux
  labels:
    logging-infra: mux
    provider: openshift
    component: mux
  parameters:
  -
    description: "The image prefix for the Fluentd image to use"
    name: IMAGE_PREFIX
    value: ${IMAGE_PREFIX_DEFAULT}
  -
    description: "The image version for the Fluentd image to use"
    name: IMAGE_VERSION
    value: ${IMAGE_VERSION_DEFAULT}
  objects:
  - apiVersion: "v1"
    kind: "DeploymentConfig"
    metadata:
      name: "logging-mux"
      labels:
        provider: openshift
        component: "mux"
    spec:
      replicas: 1
      selector:
        provider: openshift
        component: "mux"
      triggers: {}
      strategy:
        resources: {}
        rollingParams:
          intervalSeconds: 1
          timeoutSeconds: 600
          updatePeriodSeconds: 1
        type: Rolling
      template:
        metadata:
          name: mux
          labels:
            provider: openshift
            component: "mux"
        spec:
          terminationGracePeriodSeconds: 300
          serviceAccountName: aggregated-logging-fluentd
          containers:
          - name: mux
            image: ${IMAGE_PREFIX}logging-fluentd:${IMAGE_VERSION}
            imagePullPolicy: Always
            securityContext:
              privileged: true
            resources:
              limits:
                cpu: 100m
            ports:
              -
                containerPort: ${FORWARD_LISTEN_PORT}
                name: "mux-forward"
            volumeMounts:
            - name: runlogjournal
              mountPath: /run/log/journal
            - name: varlog
              mountPath: /var/log
            - name: varlibdockercontainers
              mountPath: /var/lib/docker/containers
              readOnly: true
            - name: config
              mountPath: /etc/fluent/configs.d/user
              readOnly: true
            - name: certs
              mountPath: /etc/fluent/keys
              readOnly: true
            - name: dockerhostname
              mountPath: /etc/docker-hostname
              readOnly: true
            - name: localtime
              mountPath: /etc/localtime
              readOnly: true
            - name: dockercfg
              mountPath: /etc/sysconfig/docker
              readOnly: true
            env:
            - name: "K8S_HOST_URL"
              value: ${MASTER_URL}
            - name: "ES_HOST"
              value: ${ES_HOST}
            - name: "ES_PORT"
              value: ${ES_PORT}
            - name: "ES_CLIENT_CERT"
              value: ${ES_CLIENT_CERT}
            - name: "ES_CLIENT_KEY"
              value: ${ES_CLIENT_KEY}
            - name: "ES_CA"
              value: ${ES_CA}
            - name: "OPS_HOST"
              value: ${OPS_HOST}
            - name: "OPS_PORT"
              value: ${OPS_PORT}
            - name: "OPS_CLIENT_CERT"
              value: ${OPS_CLIENT_CERT}
            - name: "OPS_CLIENT_KEY"
              value: ${OPS_CLIENT_KEY}
            - name: "OPS_CA"
              value: ${OPS_CA}
            - name: "ES_COPY"
              value: ${ES_COPY}
            - name: "ES_COPY_HOST"
              value: ${ES_COPY_HOST}
            - name: "ES_COPY_PORT"
              value: ${ES_COPY_PORT}
            - name: "ES_COPY_SCHEME"
              value: ${ES_COPY_SCHEME}
            - name: "ES_COPY_CLIENT_CERT"
              value: ${ES_COPY_CLIENT_CERT}
            - name: "ES_COPY_CLIENT_KEY"
              value: ${ES_COPY_CLIENT_KEY}
            - name: "ES_COPY_CA"
              value: ${ES_COPY_CA}
            - name: "ES_COPY_USERNAME"
              value: ${ES_COPY_USERNAME}
            - name: "ES_COPY_PASSWORD"
              value: ${ES_COPY_PASSWORD}
            - name: "OPS_COPY_HOST"
              value: ${OPS_COPY_HOST}
            - name: "OPS_COPY_PORT"
              value: ${OPS_COPY_PORT}
            - name: "OPS_COPY_SCHEME"
              value: ${OPS_COPY_SCHEME}
            - name: "OPS_COPY_CLIENT_CERT"
              value: ${OPS_COPY_CLIENT_CERT}
            - name: "OPS_COPY_CLIENT_KEY"
              value: ${OPS_COPY_CLIENT_KEY}
            - name: "OPS_COPY_CA"
              value: ${OPS_COPY_CA}
            - name: "OPS_COPY_USERNAME"
              value: ${OPS_COPY_USERNAME}
            - name: "OPS_COPY_PASSWORD"
              value: ${OPS_COPY_PASSWORD}
            - name: "USE_JOURNAL"
              value: ${USE_JOURNAL}
            - name: "JOURNAL_SOURCE"
              value: ${JOURNAL_SOURCE}
            - name: "JOURNAL_READ_FROM_HEAD"
              value: ${JOURNAL_READ_FROM_HEAD}
            - name: "FORWARD_LISTEN_PORT"
              value: ${FORWARD_LISTEN_PORT}
          volumes:
          - name: runlogjournal
            hostPath:
              path: /run/log/journal
          - name: varlog
            hostPath:
              path: /var/log
          - name: varlibdockercontainers
            hostPath:
              path: /var/lib/docker/containers
          - name: config
            configMap:
              name: logging-fluentd
          - name: certs
            secret:
              secretName: logging-fluentd
          - name: dockerhostname
            hostPath:
              path: /etc/hostname
          - name: localtime
            hostPath:
              path: /etc/localtime
          - name: dockercfg
            hostPath:
              path: /etc/sysconfig/docker
parameters:
-
  description: "Internal url for reaching the master API to query pod labels"
  name: MASTER_URL
  value: "https://kubernetes.default.svc.cluster.local"
-
  description: "Hostname (or IP) for reaching ElasticSearch to write logs"
  name: ES_HOST
  value: "logging-es"
-
  description: "Port number for reaching ElasticSearch to write logs"
  name: ES_PORT
  value: "9200"
-
  description: "Location of client certificate for authenticating to ElasticSearch to write logs"
  name: ES_CLIENT_CERT
  value: "/etc/fluent/keys/cert"
-
  description: "Location of client key for authenticating to ElasticSearch to write logs"
  name: ES_CLIENT_KEY
  value: "/etc/fluent/keys/key"
-
  description: "Location of CA cert for validating connection to ElasticSearch to write logs"
  name: ES_CA
  value: "/etc/fluent/keys/ca"
-
  description: "Hostname (or IP) for reaching ElasticSearch to write cluster logs"
  name: OPS_HOST
  value: "logging-es"
-
  description: "Port number for reaching ElasticSearch to write cluster logs"
  name: OPS_PORT
  value: "9200"
-
  description: "Location of client certificate for authenticating to ElasticSearch to write cluster logs"
  name: OPS_CLIENT_CERT
  value: "/etc/fluent/keys/cert"
-
  description: "Location of client key for authenticating to ElasticSearch to write cluster logs"
  name: OPS_CLIENT_KEY
  value: "/etc/fluent/keys/key"
-
  description: "Location of CA cert for validating connection to ElasticSearch to write cluster logs"
  name: OPS_CA
  value: "/etc/fluent/keys/ca"
-
  description: "Send a copy of the logs to an additional Elasticsearch instance."
  name: ES_COPY
  value: "false"
-
  description: "Hostname (or IP) for additional ElasticSearch"
  name: ES_COPY_HOST
  value: ""
-
  description: "Port number for additional ElasticSearch"
  name: ES_COPY_PORT
  value: ""
-
  description: "URL scheme for additional ElasticSearch - http or https - default is https"
  name: ES_COPY_SCHEME
  value: "https"
-
  description: "Location of client certificate for authenticating to additional ElasticSearch"
  name: ES_COPY_CLIENT_CERT
  value: ""
-
  description: "Location of client key for authenticating to additional ElasticSearch"
  name: ES_COPY_CLIENT_KEY
  value: ""
-
  description: "Location of CA cert for validating connection to additional ElasticSearch"
  name: ES_COPY_CA
  value: ""
-
  description: "Username for username/password auth to connection to additional ElasticSearch"
  name: ES_COPY_USERNAME
  value: ""
-
  description: "Password for username/password auth to connection to additional ElasticSearch"
  name: ES_COPY_PASSWORD
  value: ""
-
  description: "Hostname (or IP) for additional ElasticSearch to write cluster logs"
  name: OPS_COPY_HOST
  value: ""
-
  description: "Port number for additional ElasticSearch to write cluster logs"
  name: OPS_COPY_PORT
  value: ""
-
  description: "URL scheme for additional ElasticSearch to write cluster logs - http or https - default is https"
  name: OPS_COPY_SCHEME
  value: "https"
-
  description: "Location of client certificate for authenticating to additional ElasticSearch to write cluster logs"
  name: OPS_COPY_CLIENT_CERT
  value: ""
-
  description: "Location of client key for authenticating to additional ElasticSearch to write cluster logs"
  name: OPS_COPY_CLIENT_KEY
  value: ""
-
  description: "Location of CA cert for validating connectiong to additional ElasticSearch to write cluster logs"
  name: OPS_COPY_CA
  value: ""
-
  description: "Username for username/password auth to connection to additional ElasticSearch to write cluster logs"
  name: OPS_COPY_USERNAME
  value: ""
-
  description: "Password for username/password auth to connection to additional ElasticSearch to write cluster logs"
  name: OPS_COPY_PASSWORD
  value: ""
-
  description: "The prefix of the image to use."
  name: IMAGE_PREFIX_DEFAULT
  value: "openshift/origin-"
-
  description: "The version tag of the image to use."
  name: IMAGE_VERSION_DEFAULT
  value: latest
-
  description: "Use the journal as input for system logs"
  name: USE_JOURNAL
  value: "false"
-
  description: 'The journal source to use when USE_JOURNAL=true'
  name: JOURNAL_SOURCE
  value: ""
-
  description: 'Read the journal starting from the very beginning (false|true).'
  name: JOURNAL_READ_FROM_HEAD
  value: "false"
-
  description: 'The port the forward listener uses for incoming connections (targetPort: mux-forward).'
  name: FORWARD_LISTEN_PORT
  value: "24284"
